In [2]:
import numpy as np
list_ = [ 1 , 2 , 3 , 4 , 5 ]
array_list = np.array(object = list_)

''''Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.'''

In [4]:
''' Yes, there is a difference in the data type of the list_ and array_list variables. 
The list_ variable is a Python list object, whereas the array_list variable is a NumPy array object.'''

list_ = [1, 2, 3, 4, 5]
array_list = np.array(list_)

print("Data type of 'list_' variable:", type(list_))
print("Data type of 'array_list' variable:", type(array_list))


Data type of 'list_' variable: <class 'list'>
Data type of 'array_list' variable: <class 'numpy.ndarray'>


#Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [7]:
list_ = [ 1 , 2 , 3 , 4 , 5 ]
array_list=np.array(object=list_)

print("Data type of  list_")
for i in list_:
    print(type(i))
    
print("Data Type in arrayList")
for i in array_list:
    print(type(i))

Data type of  list_
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
Data Type in arrayList
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


#Q3. Considering the following changes in the variable, array_list:

In [8]:
array_list = np.array(object = list_, dtype = int)

In [11]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
array_list = np.array(object = list_, dtype = int)

print("Data type of 'list_':", type(list_))
print("Data type of 'array_list':", type(array_list))

print("Elements of 'list_':", list_)
print("Elements of 'array_list':", array_list)

print("Data type of each element in 'list_':")
for element in list_:
    print(type(element))

print("Data type of each element in 'array_list':")
for element in array_list:
    print(type(element))


Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>
Elements of 'list_': [1, 2, 3, 4, 5]
Elements of 'array_list': [1 2 3 4 5]
Data type of each element in 'list_':
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
Data type of each element in 'array_list':
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


#Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [12]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
array_list = np.array(num_list)

In [13]:
array_list

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
array_list.shape

(2, 3)

In [15]:
array_list.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [16]:
zero_array=np.zeros([3,3])

In [17]:
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
type(zero_array)

numpy.ndarray

In [19]:
zero_array=np.zeros((3,3))

In [20]:
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
type(zero_array)

numpy.ndarray

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [26]:
identy_matrix= np.eye(5)

In [28]:
identy_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])